### ISSUE TITLE
formatOnPaste

### ISSUE THREAD

**Issue by DanielPintilei** [vuejs/vetur#100]
With `"editor.formatOnPaste": true` in settings, when I paste, the code goes on a new line and the indentation messes up; if I go one step back with Ctrl+Z it looks good. Thanks.

**Comment by octref** [comment]
Screenshots please otherwise I wouldn't know what you are talking about.

**Comment by DanielPintilei** [comment]
![paste](https://cloud.githubusercontent.com/assets/9828983/24214388/fc835a04-0f3d-11e7-8155-94e4cb34a3bb.gif)

**Comment by octref** [comment]
Think that's fixed in 0.6.5.

**Comment by chasegiunta** [comment]
This is not fixed on 0.6.10
![formatting problem vetur](https://cloud.githubusercontent.com/assets/1377169/26517900/88c3729e-4268-11e7-9181-a961e94e5352.gif)

![formatting problem vetur 2](https://cloud.githubusercontent.com/assets/1377169/26517902/8d97ecf0-4268-11e7-8da3-a4c527075df4.gif)

**Comment by hypercub3d** [comment]
I'm also still experiencing this bug with the latest version of Code and the latest plugin version 0.8.5.

It's very annoying. Any chance at a fix? Or perhaps a way to disable the formatting altogether?

**Comment by DanielPintilei** [comment]
You can disable native auto formatting for vue files
`"[vue]": {
  "editor.formatOnPaste": false
 }`

**Comment by octref** [comment]
@rebornix If I remember correctly you were doing this feature, right?
Is this a bug on Vetur side or VSCode side?

**Comment by octref** [comment]
The root problem is, Vetur is given the copy-pasted text for formatting like so:

```html
    <div>
      <span>test</span>
    </div>
```

Vetur would remove all leading whitespace so it becomes:

```html
<div>
  <span>test</span>
</div>
```

@HerringtonDarkholme I'm thinking about dropping the range formatter and only provide a whole-doc formatter. Like in `vueServerMain` from `connection.onDocumentRangeFormatting` to `connection.onDocumentFormatting`. This would also stop VSCode from triggering Vetur's formatter for `formatOnPaste`.

One use case was selecting a whole region, like `<style>` and use the range formatting. But anything containing incomplete parts of multiple regions aren't handled well now. So I don't think it's that useful.
A whole-doc formatter is easier to maintain. And we can provide `vetur.format.[html/css/js].disable` so people can turn specific formatter off, if they don't like its style.

**Comment by HerringtonDarkholme** [comment]
@octref Agree.

Do you want to include this change in #363 ?

**Comment by octref** [comment]
I can do that myself. For #363 I added a comment -- let's keep it simple and pull it in first.

**Comment by octref** [comment]
Or if you want to open a separate PR. I'll start doing emmet then.
