### ISSUE TITLE
Vue Language Service crash for using attributes with hyphen in it

### ISSUE THREAD

**Issue by yurrko** [vuejs/vetur#1220]
## Info

- Platform:  Win
- Vetur version: 0.19
- VS Code version: 1.33.1

## Problem

Loaded bundled typescript@3.3.4000.
Vetur initialized
c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\services\typescriptService\sourceMap.js:144
    for (const sourceMapNode of sourceMaps[filePath]) {
                                          ^

TypeError: sourceMaps[filePath] is not iterable
    at Object.mapBackRange (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\services\typescriptService\sourceMap.js:144:43)
    at rawTemplateDiagnostics.map.diag (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\modes\template\interpolationMode.js:39:36)
    at Array.map (<anonymous>)
    at VueInterpolationMode.doValidation (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\modes\template\interpolationMode.js:35:39)
    at Object.doValidation (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\modes\template\index.js:17:80)
    at languageModes.getAllLanguageModeRangesInDocument.forEach.lmr (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\services\vls.js:345:51)
    at Array.forEach (<anonymous>)
    at VLS.doValidate (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\services\vls.js:343:72)
    at VLS.validateTextDocument (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\services\vls.js:337:34)
    at Timeout.pendingValidationRequests.(anonymous function).setTimeout [as _onTimeout] (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\services\vls.js:326:18)
[Info  - 7:55:04] Connection to server got closed. Server will restart.
[Error - 7:55:04] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\main.js:876:25)
	at Object.dispose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:71:35)
	at LanguageClient.handleConnectionClosed (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:2167:42)
	at LanguageClient.handleConnectionClosed (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\main.js:152:15)
	at closeHandler (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:2154:18)
	at CallbackList.invoke (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at closeHandler (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\main.js:226:26)
	at CallbackList.invoke (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at IPCMessageReader.fireClose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at ChildProcess.constructor.eventEmitter.on (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
	at ChildProcess.emit (events.js:187:15)
	at maybeClose (internal/child_process.js:961:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
[Error - 7:55:04] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\main.js:876:25)
	at Object.dispose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:71:35)
	at LanguageClient.handleConnectionClosed (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:2167:42)
	at LanguageClient.handleConnectionClosed (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\main.js:152:15)
	at closeHandler (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:2154:18)
	at CallbackList.invoke (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at closeHandler (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\main.js:226:26)
	at CallbackList.invoke (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at IPCMessageReader.fireClose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at ChildProcess.constructor.eventEmitter.on (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
	at ChildProcess.emit (events.js:187:15)
	at maybeClose (internal/child_process.js:961:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
[Error - 7:55:04] Request textDocument/colorPresentation failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\main.js:876:25)
	at Object.dispose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:71:35)
	at LanguageClient.handleConnectionClosed (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:2167:42)
	at LanguageClient.handleConnectionClosed (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\main.js:152:15)
	at closeHandler (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:2154:18)
	at CallbackList.invoke (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at closeHandler (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\main.js:226:26)
	at CallbackList.invoke (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at IPCMessageReader.fireClose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at ChildProcess.constructor.eventEmitter.on (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
	at ChildProcess.emit (events.js:187:15)
	at maybeClose (internal/child_process.js:961:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
Loaded bundled typescript@3.3.4000.
Vetur initialized
c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\services\typescriptService\sourceMap.js:144
    for (const sourceMapNode of sourceMaps[filePath]) {
                                          ^

TypeError: sourceMaps[filePath] is not iterable
    at Object.mapBackRange (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\services\typescriptService\sourceMap.js:144:43)
    at rawTemplateDiagnostics.map.diag (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\modes\template\interpolationMode.js:39:36)
    at Array.map (<anonymous>)
    at VueInterpolationMode.doValidation (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\modes\template\interpolationMode.js:35:39)
    at Object.doValidation (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\modes\template\index.js:17:80)
    at languageModes.getAllLanguageModeRangesInDocument.forEach.lmr (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\services\vls.js:345:51)
    at Array.forEach (<anonymous>)
    at VLS.doValidate (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\services\vls.js:343:72)
    at VLS.validateTextDocument (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\services\vls.js:337:34)
    at Timeout.pendingValidationRequests.(anonymous function).setTimeout [as _onTimeout] (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\services\vls.js:326:18)
[Info  - 7:55:08] Connection to server got closed. Server will restart.
[Error - 7:55:08] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\main.js:876:25)
	at Object.dispose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:71:35)
	at LanguageClient.handleConnectionClosed (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:2167:42)
	at LanguageClient.handleConnectionClosed (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\main.js:152:15)
	at closeHandler (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:2154:18)
	at CallbackList.invoke (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at closeHandler (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\main.js:226:26)
	at CallbackList.invoke (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at IPCMessageReader.fireClose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at ChildProcess.constructor.eventEmitter.on (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
	at ChildProcess.emit (events.js:187:15)
	at maybeClose (internal/child_process.js:961:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
[Error - 7:55:08] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\main.js:876:25)
	at Object.dispose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:71:35)
	at LanguageClient.handleConnectionClosed (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:2167:42)
	at LanguageClient.handleConnectionClosed (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\main.js:152:15)
	at closeHandler (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:2154:18)
	at CallbackList.invoke (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at closeHandler (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\main.js:226:26)
	at CallbackList.invoke (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at IPCMessageReader.fireClose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at ChildProcess.constructor.eventEmitter.on (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
	at ChildProcess.emit (events.js:187:15)
	at maybeClose (internal/child_process.js:961:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
[Error - 7:55:08] Request textDocument/colorPresentation failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\main.js:876:25)
	at Object.dispose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:71:35)
	at LanguageClient.handleConnectionClosed (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:2167:42)
	at LanguageClient.handleConnectionClosed (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\main.js:152:15)
	at closeHandler (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:2154:18)
	at CallbackList.invoke (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at closeHandler (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\main.js:226:26)
	at CallbackList.invoke (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at IPCMessageReader.fireClose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at ChildProcess.constructor.eventEmitter.on (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
	at ChildProcess.emit (events.js:187:15)
	at maybeClose (internal/child_process.js:961:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
Loaded bundled typescript@3.3.4000.
Vetur initialized
c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\services\typescriptService\sourceMap.js:144
    for (const sourceMapNode of sourceMaps[filePath]) {
                                          ^

TypeError: sourceMaps[filePath] is not iterable
    at Object.mapBackRange (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\services\typescriptService\sourceMap.js:144:43)
    at rawTemplateDiagnostics.map.diag (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\modes\template\interpolationMode.js:39:36)
    at Array.map (<anonymous>)
    at VueInterpolationMode.doValidation (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\modes\template\interpolationMode.js:35:39)
    at Object.doValidation (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\modes\template\index.js:17:80)
    at languageModes.getAllLanguageModeRangesInDocument.forEach.lmr (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\services\vls.js:345:51)
    at Array.forEach (<anonymous>)
    at VLS.doValidate (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\services\vls.js:343:72)
    at VLS.validateTextDocument (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\services\vls.js:337:34)
    at Timeout.pendingValidationRequests.(anonymous function).setTimeout [as _onTimeout] (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\services\vls.js:326:18)
[Info  - 7:55:13] Connection to server got closed. Server will restart.
[Error - 7:55:13] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\main.js:876:25)
	at Object.dispose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:71:35)
	at LanguageClient.handleConnectionClosed (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:2167:42)
	at LanguageClient.handleConnectionClosed (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\main.js:152:15)
	at closeHandler (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:2154:18)
	at CallbackList.invoke (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at closeHandler (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\main.js:226:26)
	at CallbackList.invoke (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at IPCMessageReader.fireClose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at ChildProcess.constructor.eventEmitter.on (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
	at ChildProcess.emit (events.js:187:15)
	at maybeClose (internal/child_process.js:961:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
[Error - 7:55:13] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\main.js:876:25)
	at Object.dispose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:71:35)
	at LanguageClient.handleConnectionClosed (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:2167:42)
	at LanguageClient.handleConnectionClosed (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\main.js:152:15)
	at closeHandler (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:2154:18)
	at CallbackList.invoke (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at closeHandler (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\main.js:226:26)
	at CallbackList.invoke (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at IPCMessageReader.fireClose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at ChildProcess.constructor.eventEmitter.on (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
	at ChildProcess.emit (events.js:187:15)
	at maybeClose (internal/child_process.js:961:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
[Error - 7:55:13] Request textDocument/colorPresentation failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\main.js:876:25)
	at Object.dispose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:71:35)
	at LanguageClient.handleConnectionClosed (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:2167:42)
	at LanguageClient.handleConnectionClosed (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\main.js:152:15)
	at closeHandler (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:2154:18)
	at CallbackList.invoke (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at closeHandler (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\main.js:226:26)
	at CallbackList.invoke (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at IPCMessageReader.fireClose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at ChildProcess.constructor.eventEmitter.on (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
	at ChildProcess.emit (events.js:187:15)
	at maybeClose (internal/child_process.js:961:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
Loaded bundled typescript@3.3.4000.
Vetur initialized
c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\services\typescriptService\sourceMap.js:144
    for (const sourceMapNode of sourceMaps[filePath]) {
                                          ^

TypeError: sourceMaps[filePath] is not iterable
    at Object.mapBackRange (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\services\typescriptService\sourceMap.js:144:43)
    at rawTemplateDiagnostics.map.diag (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\modes\template\interpolationMode.js:39:36)
    at Array.map (<anonymous>)
    at VueInterpolationMode.doValidation (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\modes\template\interpolationMode.js:35:39)
    at Object.doValidation (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\modes\template\index.js:17:80)
    at languageModes.getAllLanguageModeRangesInDocument.forEach.lmr (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\services\vls.js:345:51)
    at Array.forEach (<anonymous>)
    at VLS.doValidate (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\services\vls.js:343:72)
    at VLS.validateTextDocument (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\services\vls.js:337:34)
    at Timeout.pendingValidationRequests.(anonymous function).setTimeout [as _onTimeout] (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\services\vls.js:326:18)
[Info  - 7:55:17] Connection to server got closed. Server will restart.
[Error - 7:55:17] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\main.js:876:25)
	at Object.dispose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:71:35)
	at LanguageClient.handleConnectionClosed (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:2167:42)
	at LanguageClient.handleConnectionClosed (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\main.js:152:15)
	at closeHandler (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:2154:18)
	at CallbackList.invoke (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at closeHandler (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\main.js:226:26)
	at CallbackList.invoke (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at IPCMessageReader.fireClose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at ChildProcess.constructor.eventEmitter.on (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
	at ChildProcess.emit (events.js:187:15)
	at maybeClose (internal/child_process.js:961:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
[Error - 7:55:17] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\main.js:876:25)
	at Object.dispose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:71:35)
	at LanguageClient.handleConnectionClosed (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:2167:42)
	at LanguageClient.handleConnectionClosed (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\main.js:152:15)
	at closeHandler (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:2154:18)
	at CallbackList.invoke (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at closeHandler (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\main.js:226:26)
	at CallbackList.invoke (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at IPCMessageReader.fireClose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at ChildProcess.constructor.eventEmitter.on (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
	at ChildProcess.emit (events.js:187:15)
	at maybeClose (internal/child_process.js:961:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
[Error - 7:55:17] Request textDocument/colorPresentation failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\main.js:876:25)
	at Object.dispose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:71:35)
	at LanguageClient.handleConnectionClosed (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:2167:42)
	at LanguageClient.handleConnectionClosed (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\main.js:152:15)
	at closeHandler (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:2154:18)
	at CallbackList.invoke (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at closeHandler (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\main.js:226:26)
	at CallbackList.invoke (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at IPCMessageReader.fireClose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at ChildProcess.constructor.eventEmitter.on (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
	at ChildProcess.emit (events.js:187:15)
	at maybeClose (internal/child_process.js:961:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
Loaded bundled typescript@3.3.4000.
Vetur initialized
c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\services\typescriptService\sourceMap.js:144
    for (const sourceMapNode of sourceMaps[filePath]) {
                                          ^

TypeError: sourceMaps[filePath] is not iterable
    at Object.mapBackRange (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\services\typescriptService\sourceMap.js:144:43)
    at rawTemplateDiagnostics.map.diag (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\modes\template\interpolationMode.js:39:36)
    at Array.map (<anonymous>)
    at VueInterpolationMode.doValidation (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\modes\template\interpolationMode.js:35:39)
    at Object.doValidation (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\modes\template\index.js:17:80)
    at languageModes.getAllLanguageModeRangesInDocument.forEach.lmr (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\services\vls.js:345:51)
    at Array.forEach (<anonymous>)
    at VLS.doValidate (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\services\vls.js:343:72)
    at VLS.validateTextDocument (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\services\vls.js:337:34)
    at Timeout.pendingValidationRequests.(anonymous function).setTimeout [as _onTimeout] (c:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\server\dist\services\vls.js:326:18)
[Error - 7:55:21] Connection to server got closed. Server will not be restarted.
[Error - 7:55:21] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\main.js:876:25)
	at Object.dispose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:71:35)
	at LanguageClient.handleConnectionClosed (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:2167:42)
	at LanguageClient.handleConnectionClosed (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\main.js:152:15)
	at closeHandler (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:2154:18)
	at CallbackList.invoke (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at closeHandler (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\main.js:226:26)
	at CallbackList.invoke (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at IPCMessageReader.fireClose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at ChildProcess.constructor.eventEmitter.on (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
	at ChildProcess.emit (events.js:187:15)
	at maybeClose (internal/child_process.js:961:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
[Error - 7:55:21] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\main.js:876:25)
	at Object.dispose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:71:35)
	at LanguageClient.handleConnectionClosed (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:2167:42)
	at LanguageClient.handleConnectionClosed (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\main.js:152:15)
	at closeHandler (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:2154:18)
	at CallbackList.invoke (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at closeHandler (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\main.js:226:26)
	at CallbackList.invoke (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at IPCMessageReader.fireClose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at ChildProcess.constructor.eventEmitter.on (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
	at ChildProcess.emit (events.js:187:15)
	at maybeClose (internal/child_process.js:961:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
[Error - 7:55:21] Request textDocument/colorPresentation failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\main.js:876:25)
	at Object.dispose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:71:35)
	at LanguageClient.handleConnectionClosed (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:2167:42)
	at LanguageClient.handleConnectionClosed (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\main.js:152:15)
	at closeHandler (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-languageclient\lib\client.js:2154:18)
	at CallbackList.invoke (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at closeHandler (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\main.js:226:26)
	at CallbackList.invoke (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at IPCMessageReader.fireClose (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at ChildProcess.constructor.eventEmitter.on (C:\Users\denisevich.yuv\.vscode\extensions\octref.vetur-0.19.0\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
	at ChildProcess.emit (events.js:187:15)
	at maybeClose (internal/child_process.js:961:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)

## Reproducible Case

run any project

**Comment by HonLuk** [comment]
same problem on mac os.

**Comment by de1ck** [comment]
same problem on win10 vetur 0.19.0

**Comment by yurrko** [comment]
temporary solution
"vetur.experimental.templateInterpolationService": false,

**Comment by adityamandal** [comment]
Same on my PC as well 😢 
It keeps on crashing... Is there a way to revert to an older build?

**Comment by de1ck** [comment]
> Same on my PC as well 😢
> It keeps on crashing... Is there a way to revert to an older build?

@adityamandal on vuetur extensions setting select other version

**Comment by adityamandal** [comment]
> > Same on my PC as well 😢
> > It keeps on crashing... Is there a way to revert to an older build?
> 
> @adityamandal on vuetur extensions setting select other version

I tried this fix provided by yurrko.. it works now 😄 
https://github.com/vuejs/vetur/issues/1220#issuecomment-486083369

**Comment by ridesky** [comment]
Rollback to  0.18.1 . . . .  
(这是一个大型的翻车现场

**Comment by bh4jjs** [comment]
same problem, rollback to 0.18.1

**Comment by nivabecassis** [comment]
> > Same on my PC as well 😢
> > It keeps on crashing... Is there a way to revert to an older build?
> 
> @adityamandal on vuetur extensions setting select other version

Rolling back to 0.18.1 works for me. Don't forget to disable extension auto-update in your settings or else it will update automatically on vs code restart.

**Comment by wfzong** [comment]
same problem on win10 vetur 0.19.0, vscode 1.33.1

**Comment by KevisLuo** [comment]
rollback to 0.18.1 failed
1. install 0.18.1
2. reload vs code
3. reinstall 0.19 automatically

**Comment by de1ck** [comment]
> rollback to 0.18.1 failed
> 
> 1. install 0.18.1
> 2. reload vs code
> 3. reinstall 0.19 automatically
@KevisLuo 
![image](https://user-images.githubusercontent.com/26627486/56643777-dd9d6a80-66ac-11e9-932b-00d1a22ec8c0.png)

**Comment by KevisLuo** [comment]
@de1ck thank you, it works

**Comment by LolliDepp** [comment]
+1 doesn't work for me either

```
TypeError: sourceMaps[filePath] is not iterable
    at Object.mapBackRange (c:\Users\FabioLolli\.vscode\extensions\octref.vetur-0.19.0\server\dist\services\typescriptService\sourceMap.js:144:43)
    at rawTemplateDiagnostics.map.diag (c:\Users\FabioLolli\.vscode\extensions\octref.vetur-0.19.0\server\dist\modes\template\interpolationMode.js:39:36)
    at Array.map (<anonymous>)
    at VueInterpolationMode.doValidation (c:\Users\FabioLolli\.vscode\extensions\octref.vetur-0.19.0\server\dist\modes\template\interpolationMode.js:35:39)
    at Object.doValidation (c:\Users\FabioLolli\.vscode\extensions\octref.vetur-0.19.0\server\dist\modes\template\index.js:17:80)
    at languageModes.getAllLanguageModeRangesInDocument.forEach.lmr (c:\Users\FabioLolli\.vscode\extensions\octref.vetur-0.19.0\server\dist\services\vls.js:345:51)
    at Array.forEach (<anonymous>)
    at VLS.doValidate (c:\Users\FabioLolli\.vscode\extensions\octref.vetur-0.19.0\server\dist\services\vls.js:343:72)
    at VLS.validateTextDocument (c:\Users\FabioLolli\.vscode\extensions\octref.vetur-0.19.0\server\dist\services\vls.js:337:34)
    at Timeout.pendingValidationRequests.(anonymous function).setTimeout [as _onTimeout] (c:\Users\FabioLolli\.vscode\extensions\octref.vetur-0.19.0\server\dist\services\vls.js:326:18)
```

I really want to get that TS template interpolation working :P

**Comment by nj-neer** [comment]
Same issue here @yurrko solution work as a temporary fix

**Comment by cockneychops** [comment]
Same issue here...

Win 10
VSCode 1.33.1
Vetur 0.19.0

Using @yurrko fix for now

**Comment by octref** [comment]
The root cause should be fixed with #1222.

**Comment by octref** [comment]
Actually that's a different codepath

**Comment by dhonx** [comment]
@octref Still happen... What is the latest version that works well?

**Comment by rishpandey** [comment]
This still happens. I am on v0.24.0.

**Comment by octref** [comment]
Please open new issues with reproducible steps then.

**Comment by armenr** [comment]
There is no formatter for 'vue' files installed.

Seeing this with Vetur on VSCode Version: 1.55.0-insider + Vetur v0.33.1
OSX
