### ISSUE TITLE
Unexpected Vetur error messages

### ISSUE THREAD

**Issue by chanlito** [vuejs/vetur#1221]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.19.0
- VS Code version: 1.33.1

## Problem

```vue
<template>
  <v-container grid-list-lg>
    Nice
  </v-container>
</template>

<script lang="ts">
import Vue from 'vue';
import { VContainer } from 'vuetify/lib';

export default Vue.extend({
  components: {
    VContainer,
  },
});
</script>

```

The above component causes the error below:

<img width="927" alt="Screen Shot 2019-04-24 at 12 26 41 PM" src="https://user-images.githubusercontent.com/15667259/56634443-3f99a800-668c-11e9-941b-07d380834577.png">

**Comment by shenxiang11** [comment]
<img width="721" alt="屏幕快照 2019-04-24 下午2 45 47" src="https://user-images.githubusercontent.com/17292115/56638060-bee4a700-669f-11e9-9af6-08c303a7d8a0.png">
Yes, I've met the question as you too.

**Comment by HonLuk** [comment]
I use version 0.18.1 for now.waiting for new release.

**Comment by chanlito** [comment]
Right now I turned off `Experimental: Template Interpolation Service`.

**Comment by dukferradj** [comment]
> Right now I turned off `Experimental: Template Interpolation Service`.

Worked for me. Thanks !

**Comment by aljaxus** [comment]
I'm sorry, where can you edit this setting ?

**Comment by dukferradj** [comment]
@aljaxus  In your settings.json file you can add `"vetur.experimental.templateInterpolationService": false`

**Comment by aljaxus** [comment]
> @aljaxus In your settings.json file you can add `"vetur.experimental.templateInterpolationService": false`
Thanks. I just found it. I guess I scrolled by when searching for it...

For anyone else that might be searching for it;
Toolbar > File > Preferences > Settings -> (sidebar in settings) Extensions > Vetur > "Experimental: Template Interpolation Service" toggle at the very start of Vetur section (as @chanlito pointed out [here](https://github.com/vuejs/vetur/issues/1221#issuecomment-486095703))

Or just edit the `settings.json` file, located at "~/.config/Code/User/settings.json" on Linux, and add the `"vetur.experimental.templateInterpolationService": false` line (as @dukferradj pointed out [here](https://github.com/vuejs/vetur/issues/1221#issuecomment-486110709))

**Comment by rockshenhua** [comment]
me too

**Comment by aljaxus** [comment]
> me too

Read [my reply](https://github.com/vuejs/vetur/issues/1221#issuecomment-486112998) to "fix" the issue.

**Comment by unclexiao** [comment]
Me too. And after I add this config: 
```
"vetur.experimental.templateInterpolationService": false
```

It is back to working again!   Thanks ~ @dukferradj

**Comment by hellomikes** [comment]
@dukferradj awesome, thanks for posting that, it solved my issue!

FYI, for the sake of debugging this issue, I was getting the following:

![image](https://user-images.githubusercontent.com/48011140/56645176-17527f00-6675-11e9-97bf-31dd7230d4c5.png)

This seems to be occurring for every computed property I'm generating via Vuex's `mapState` or `mapGetter`, and even appeared for a regular method that I have defined too

**Comment by huyajie** [comment]
![image](https://user-images.githubusercontent.com/7566894/56645442-42a68f80-66b0-11e9-98d6-e8727f46a179.png)

**Comment by huyajie** [comment]
> ![image](https://user-images.githubusercontent.com/7566894/56645442-42a68f80-66b0-11e9-98d6-e8727f46a179.png)
> What's the problem?
> Opening all files today is like this
> 
> help

"vetur.validation.template": false
Add this to it.
But I don't know why.

**Comment by golopot** [comment]
This bug happens when the a attribute name contains a hypen, e.g.
```vue
<template>
  <div foo-bar="baz"/>
</template>
```

**Comment by victorgarciaesgi** [comment]
I have the error too. It's appening when a prop or event have a hyphen or comma.
Cases appening for me:
```html
<div 
 :max-bounds="maxBounds"
 @event-created="createEvent"
 @update:center="centerUpdate">
</div>
```

**Comment by kouchao** [comment]
Appear at 0.19.0, retreat to 0.18.1

**Comment by ktsn** [comment]
I already made a PR #1222.

**Comment by victorgarciaesgi** [comment]
@ktsn It's not only hyphens, I have the problem with colons too

**Comment by ktsn** [comment]
That's the same cause. The PR covers your case.

**Comment by victorgarciaesgi** [comment]
@ktsn Allright, thanks! 💯

**Comment by octref** [comment]
Fixed via #1222.

**Comment by frizar** [comment]
Still not fixed
![image](https://user-images.githubusercontent.com/8735701/56715454-644f5780-6740-11e9-9fc8-b84938f1700e.png)

**Comment by valerijmedvid** [comment]
Vetur version 0.19.1
<img width="353" alt="Screenshot 2019-04-25 at 09 16 08" src="https://user-images.githubusercontent.com/40756610/56716561-f3597100-673a-11e9-8b5f-874d84a90870.png">

**Comment by aljaxus** [comment]
@frizar @valerijmedvid 
Anyhow... [temp fix](https://github.com/vuejs/vetur/issues/1221#issuecomment-486112998)

**Comment by zhangkun95** [comment]
Change vetur settings
Uncheck the following
Validation: Template
Validate vue-html in using eslint-plugin-vue

![image](https://user-images.githubusercontent.com/44808686/56777730-9e366180-6805-11e9-8d6f-cb2a5fc87f41.png)

https://github.com/vuejs/vetur/issues/1237#issuecomment-486890760

**Comment by MattixNow** [comment]
Up !

**Comment by a15965734368** [comment]
Vetur version 0.32.0  setting.json  add this config:
`"vetur.validation.interpolation": false`

**Comment by yoyo930021** [comment]
I will lock this issue.
Please open a new issue when you have problem.
