### ISSUE TITLE
Intellisense / type checking stopped working in v0.22.4

### ISSUE THREAD

**Issue by Soresu** [vuejs/vetur#1449]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows 10 x64
- Vetur version: 0.22.4
- VS Code version: 1.38.1
- Already reinstalled Visual Studio Code, Vetur
- Happens on multiple PC
- Tried to remove other plugins

## Problem

Intellisense stopped working properly in Vue files. Although it works in the first opened vue file or if it was opened in the previous session.
Downgrading to Vetur 0.22.3 fixed the issue.

## Reproducible Case

1. Close all tabs in the current project
2. Close and open Visual Studio Code
3. Open a vue file
4. Wait until the plugins are loaded
5. Hovering over/Ctrl+space at imported objects, variables doesn't show any info
6. Close and open Visual Studio Code
7. Intellisense works in the previously opened file

**Comment by borradaniele** [comment]
Same here, linking between files does not work with cmd and intellisense does not shows up, already tried to uninstall and reinstall.
Seems like occasionally it starts working again for some times and then stops again, not sure about the events chain that causes this tho.

Platform: Mac OS Mojave 10.14.6
VS Code version: 1.38.1
Vetur version: 0.22.4

If you need more info or log let me know.

**Comment by alexsasharegan** [comment]
Same on Linux.

Vetur: 0.22.4

**VSCode Stats:**
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:30:08.229Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.0.0-31-generic

**Comment by yoyo930021** [comment]
https://github.com/vuejs/vetur/issues/1317#issuecomment-537488062

**Comment by Sheng-Long** [comment]
Same issue for me, although it always seems to work in at least one file, but not the others

**Comment by huangysss** [comment]
+1

**Comment by hkk2018** [comment]
+1

**Comment by matthew-ch** [comment]
Similar issue for my project using typescript.

VSCode version: 1.39.0
OS: macOS Catalina 10.15
Vetur version: 0.22.4

Downgrading to 0.22.3 works.

**Comment by Ttou** [comment]
+1

**Comment by sppera** [comment]
+1

- Platform: Linux fedora 5.2.18-200.fc30.x86_64
- Vetur version: 0.22.4
- VS Code version: 1.39.1

**Comment by wfischer42** [comment]
Similar issue.
Specifically, TypeScript errors only show up in the first file I open after launching VSCode.
This was true using both TSLint Vue and ESLint to validate. 

Downgrading to 0.22.3 worked for me too.

**Comment by SunshowerC** [comment]
same here. 
Platform: Mac
Vetur version: 0.22.4

**Comment by imakan** [comment]
Downgrading to 0.22.3 worked for me

**Comment by Yancy1028** [comment]
my english is bad,but I know how to reproduce the problem.
in my new application,
1st use any "*.vue" file in "router.ts",and close all opened vue file,
2nd resert VSCode,and then open a normal vue file,that's ok,  
3rd open any one vue file is "router.ts" used.that is not work.

it's look like ,vue file is import on other *".ts" file,vue IntelliSense not work.

**Comment by amirafzali** [comment]
Platform: Mac
Vetur version: 0.22.4

Only one file has working intellisense at a given time. Language server keeps crashing.
Downgrading to 0.22.3 fixed the problem.

**Comment by mahoek** [comment]
Same here on Mac OS..

Vue Language Server was only getting empty content in `textDocument/hover` responses.

0.22.3 fixes this also for me.

**Comment by rchl** [comment]
Guys, there is no need for confirmation. Just use the reaction icon if you need to say "me too"

**Comment by tomasbjerre** [comment]
Same here. It works for a while after reinstall.
**Workaround:** CTRL-P and type: `> Reinstall Extension` and pick Vetur.

**Comment by petternordholm** [comment]
Hi!

Did some debugging on this issue. AFAIK, the problem is related to:
`javascript.ts:languageServiceIncludesFile`

This method is called with the `.vue` file and return false. This will bypass validation, hovering, etc. and return an empty result.

For instance:
```
    doValidation(doc: TextDocument): Diagnostic[] {
      const { scriptDoc, service } = updateCurrentVueTextDocument(doc);
      if (!languageServiceIncludesFile(service, doc.uri)) {
        return [];
      }
```

In our tsconfig.json, we are not including vue file since these will be pulled in by the compiler anyway when our entry point ts files are compiled.

So,
```
export function languageServiceIncludesFile(ls: ts.LanguageService, documentUri: string): boolean {
  const filePaths = ls.getProgram()!.getRootFileNames();
  const filePath = getFilePath(documentUri);
  const found = filePaths.includes(filePath);
  return found;
}
```

filePaths will not contain our vue files, only ts files, and the method will return false.

**Comment by yoyo930021** [comment]
> Hi!
> 
> Did some debugging on this issue. AFAIK, the problem is related to:
> `javascript.ts:languageServiceIncludesFile`
> 
> This method is called with the `.vue` file and return false. This will bypass validation, hovering, etc. and return an empty result.
> 
> For instance:
> 
> ```
>     doValidation(doc: TextDocument): Diagnostic[] {
>       const { scriptDoc, service } = updateCurrentVueTextDocument(doc);
>       if (!languageServiceIncludesFile(service, doc.uri)) {
>         return [];
>       }
> ```
> 
> In our tsconfig.json, we are not including vue file since these will be pulled in by the compiler anyway when our entry point ts files are compiled.
> 
> So,
> 
> ```
> export function languageServiceIncludesFile(ls: ts.LanguageService, documentUri: string): boolean {
>   const filePaths = ls.getProgram()!.getRootFileNames();
>   const filePath = getFilePath(documentUri);
>   const found = filePaths.includes(filePath);
>   return found;
> }
> ```
> 
> filePaths will not contain our vue files, only ts files, and the method will return false.

#1450 PR will fixed.

**Comment by petternordholm** [comment]
Kudos @yoyo930021 .. Great work! Hope we can get this PR merged ASAP! 

It is driving me crazy. I will apply your changes on my local VLS

**Comment by josh-hemphill** [comment]
I want to make sure this is my only issue, did this also break all emmet/bracket-closing functions as well?

**Comment by tomasbjerre** [comment]
If anyone wants to install a previous version, you can install it like this:
![image](https://user-images.githubusercontent.com/439571/67067562-122f4200-f177-11e9-8777-14061e991632.png)

**Comment by octref** [comment]
Should be fixed in 0.22.5. Thanks to @yoyo930021 for fixing it! Sorry I had been traveling and just catching up with notifications.

**Comment by GordonBlahut** [comment]
0.22.5 still doesn't fix this for me. Downgrading to 0.22.3 works.

Windows 10 x64, VS Code 1.39.2
Tried uninstalling Vetur, deleting from extensions directory and reinstalling.

**Comment by octref** [comment]
@GordonBlahut Does it reproduce on the sample project? https://github.com/octref/veturpack
If not, can you open a new bug report with reproducible steps?

**Comment by douglasg14b** [comment]
I'm also having this issue, v0.22.4 & 0.22.5 both have this issue for me.

Manually downgrading to v0.22.2 resolves it.

**Comment by douglasg14b** [comment]
Why is the issue closed?

**Comment by Neme12** [comment]
I'm still encountering this issue after upgrading to 0.22.5. In fact it no longer works even in the first opened file.

**Comment by matthew-ch** [comment]
For me version 0.22.5 works, both in ts and non-ts projects.

**Comment by deankinane** [comment]
InelliSense now completely broken in 0.22.5.
Doesn't work in first open file or file opened from previous session.

**Comment by Soresu** [comment]
The new 0.22.5 still has the problem. Moreover, step 7 of the reproducible case is now broken too.

**Comment by yoyo930021** [comment]
I think to have another problem causes on this issue.
Maybe #1469 

If (use windows and break) {
    pick +1 reaction.
} else {
    pick -1 reaction.
}

**Comment by yoyo930021** [comment]
I think have an error fix on #1450.

I fix it on #1472.
Have anyone can verify it?

**Comment by praveenpuglia** [comment]
I don't know. I used 0.22.5 for most part of the day today. Haven't seen problems. Help me see the problem?

**Comment by petternordholm** [comment]
> I don't know. I used 0.22.5 for most part of the day today. Haven't seen problems. Help me see the problem?

@praveenpuglia I think the problem is related to windows and windows filepaths. Are you running VSCode on linux or mac ?

**Comment by praveenpuglia** [comment]
macOS Catalina - 10.15.1

**Comment by octref** [comment]
Fix for Windows is released on 0.22.6.

**Comment by Soresu** [comment]
@octref Seems like 0.22.6 fixed the issue.

**Comment by lzinga** [comment]
I believe I am still getting this issue. I have been able to get the import intellisense paths to work by using [this post](https://www.reddit.com/r/vuejs/comments/dr6zj6/getting_webpack_alias_to_work_in_vue_files_for/) on reddit. However when I try to access anything from the imported file there is no intellisense.
Inside the imported file the following exists.
```js
import axios from 'axios'

export const test = {
	async get(id) {
		// ..
	}
}
```
Intellisense doesn't even exist for any Vue elements either. I am at a complete halt in my development because of this issue that I can't seem to get past. I am somewhat new to dealing with js but have been programming for quite a few years now and have been frustrated for over a week now.

**Comment by yoyo930021** [comment]
@lzinga please give more info for this.
Create new issue, and use issue template.

**Comment by Niekvdm** [comment]
Issue arrised again in 0.23.0 see #1589

**Comment by ykamal** [comment]
Bumping this. Same problem. Suddenly stopped working. 
Version: 1.45.0 (user setup)
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T16:18:48.860Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
Installing/Reinstalling Vetur didn't help.
