### ISSUE TITLE
Automatic Import Organisation not working

### ISSUE THREAD

**Issue by blake-newman** [vuejs/vetur#843]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: 
- Vetur version: 0.12.1
- VS Code version: 1.25.1

## Problem

Automatic organization / cleans up of imports does not work in Vue files. 

## Reproducible Case

Run `alt + shift + o`  (Linux) running in TS/JS file will automatically clean up imports and organize them. 

## Action

I am happy to do the work, this may not be a problem in Vetur itself, but somewhere else. However, i am not 100% sure where to look. @octref

**Comment by octref** [comment]
This is something relatively new & just getting added to the LSP protocol.

https://microsoft.github.io/language-server-protocol/specification#textDocument_codeAction

I haven't figured out a way to implement it yet...I'll look into it.

**Comment by TimeBandit** [comment]
We are seeing this also

**Comment by beeplin** [comment]
Any update on this? Really enjoy auto organization of imports in JS but it is frustrating not being able to use it in VUE files.

**Comment by yoyo930021** [comment]
Fixed in #2635

**Comment by Karolis92** [comment]
was this released? It still does not work for me with v0.34.1

**Comment by Glandos** [comment]
GitHub says it was included in `0.32.0`, but it is only working with `Organize Imports` manual command, and not with:
```json
"editor.codeActionsOnSave": {
      "source.organizeImports": true
  }
```

**Comment by yoyo930021** [comment]
> GitHub says it was included in `0.32.0`, but it is only working with `Organize Imports` manual command, and not with:
> 
> ```json
> "editor.codeActionsOnSave": {
>       "source.organizeImports": true
>   }
> ```

Follow https://github.com/vuejs/vetur/issues/3018

**Comment by Karolis92** [comment]
for me it doesn't work with shortcut either...

**Comment by triforcely** [comment]
@Karolis92 this issue is pretty old but there is a fresh one that describes what you are experiencing https://github.com/vuejs/vetur/issues/3020
