### ISSUE TITLE
Prettier-Eslint format failed

### ISSUE THREAD

**Issue by yukipastelcat** [vuejs/vetur#939]
- [✅] I have searched through existing issues
- [✅] I have read through [docs](https://vuejs.github.io/vetur)
- [✅] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: v0.13.0
- VS Code version: 1.28.2 (user setup

## Problem

```
[Error - 10:57:00 AM] prettier-eslint [ERROR]:
Prettier-Eslint format failed
[Error - 10:57:00 AM] No parser could be inferred for file: c:\Users\<user-name>\Documents\Repositories\project-x\pages
```
## Reproducible Case

`<script>` section doesn't format at all. My eslint settings:
```json
{
  "root": true,
  "env": {
    "browser": true,
    "node": true
  },
  "parserOptions": {
    "parser": "babel-eslint"
  },
  "extends": ["plugin:vue/recommended", "airbnb-base"],
  "plugins": ["vue"],
  "rules": {
    "no-console": "warn",
    "no-debugger": "warn"
  },
  "settings": {
    "import/resolver": {
      "nuxt": {
        "extensions": [".js", ".vue"]
      }
    }
  }
}
```
My prettier settings:
```json
{
  "singleQuote": true,
  "trailingComma": "all",
  "arrowParens": "always",
  "printWidth": 80,
  "tabWidth": 2,
  "semi": true,
  "bracketSpacing": true
}
```

Vetur settings are set to default, eslint and prettier settings for VSCode:
```json
"prettier.stylelintIntegration": true,
"eslint.autoFixOnSave": true,
"prettier.eslintIntegration": true,
"eslint.validate": [
    "javascript",
    "javascriptreact",
    {
      "language": "vue",
      "autoFix": true
    }
  ]
```

Prettier is installed locally, so [#498](https://github.com/prettier/prettier-vscode/issues/498) doesn't help.

**Comment by franciscosucre** [comment]
I am having the same problem, it worked before and suddenly it stopped working. Similar settings.

**Comment by xsbchen** [comment]
@octref Is there an ETA for this?

**Comment by octref** [comment]
This should be fixed by 0.14.0. If not, feel free to reopen or open new issues.

**Comment by johnwebbcole** [comment]
I'm running 0.14.0, and I still see this issue.  Not sure how to debug it, but I did set `vetur.trace.server: "verbose"`.  Here's the output:

```
[Trace - 11:46:04 AM] Sending request 'textDocument/formatting - (2352)'.
Params: {
    "textDocument": {
        "uri": "file:///d%3A/src/mobile-footer-layout/src/components/MobileFooterTabs.vue"
    },
    "options": {
        "tabSize": 4,
        "insertSpaces": true
    }
}


[Trace - 11:46:04 AM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "Prettier format failed"
}


Prettier format failed
[Trace - 11:46:04 AM] Received notification 'window/logMessage'.
Params: {
    "type": 1,
    "message": "Cannot read property 'tabWidth' of null"
}
```
If I add a `prettier.config.js` file, the problem goes away.  Oddly though, my `prettier.config.js` file does
not set `tabWdith`.

```javascript
module.exports = {
  printWidth: 100,
  singleQuote: false
};

```

**Comment by Coder-256** [comment]
@octref Might this be the issue?

https://github.com/vuejs/vetur/commit/20308083d1d014475a62bace88941f2f389a4c11#diff-688041a1cacb904fa83a9c09faec7b38R64

**Comment by octref** [comment]
I see the problem. When prettier cannot resolve a config, it returns null instead of an empty object. I've pushed a fix and am queuing a new release.

**Comment by octref** [comment]
Try 0.14.1.
